version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - ">= 3.6.a, < 3.7"
  - dependency-name: org.owasp.dependencycheck
    versions:
    - 6.1.0
    - 6.1.5
  - dependency-name: org.springframework.boot:spring-boot-gradle-plugin
    versions:
    - 2.4.2
    - 2.4.3
    - 2.4.4
    - 2.4.5
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.7
    - 3.8.0
    - 3.9.0
  - dependency-name: org.jetbrains.kotlin:kotlin-allopen
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.kotlin:kotlin-gradle-plugin
    versions:
    - 1.4.21-2
    - 1.4.31
    - 1.4.32
  - dependency-name: io.sentry:sentry-logback
    versions:
    - 4.0.0
    - 4.1.0
    - 4.3.0
  - dependency-name: com.auth0:jwks-rsa
    versions:
    - 0.17.0
  - dependency-name: io.opentracing.contrib:opentracing-spring-jaeger-web-starter
    versions:
    - 3.3.1
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.1
    - 3.13.0
    - 3.14.0
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
