#!/usr/bin/env bash

# This assumes you have provisioned the machine
ktlint --apply-to-idea-project

# Generate local development configuration
pushd src/main/resources/
./setup-local-development
echo "Local development configuration"
popd
