#!/usr/bin/env bash

# This assumes you have provisioned the machine
ktlint --apply-to-idea-project -y

pushd frontend/
echo "Adding bit.dev to npm registry"
echo "always-auth=true" >> .npmrc
echo "@bit:registry=https://node.bit.dev" >> .npmrc
echo "//node.bit.dev/:_authToken={$(bo show credential concourse-main bit token)}" >> .npmrc
echo "Completed adding bit.dev to npm registry"
popd
