---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: java
    tag: '8'

inputs:
- name: source
- name: version

outputs:
- name: dist

caches:
- path: source/.gradle

params:
  CYPRESS_INSTALL_BINARY: 0
  GRADLE_USER_HOME: .gradle

run:
  path: sh
  args:
  - -c
  - |-
    set -eu

    version=$(cat version/tag)

    (
    cd source
    ./gradlew -Pversion="$version" clean build --rerun-tasks
    )

    cp -a source/* dist/
