---
groups:
- name: all
  jobs:
  - build

jobs:
- name: build
  serial: true
  plan:
  - get: once-per-weekday
    trigger: true
  - get: source
    trigger: true
  - put: version
    params:
      bump: minor
    resource: version-lti
  - task: build
    file: source/pipeline/build.yml
  - put: image
    resource: image-lti
    params:
      build: dist
      additional_tags: version/version

resources:
- name: source
  type: git
  source:
    branch: master
    private_key: ((lti-repo-key))
    uri: git@github.com:boclips/lti.git

- name: version-lti
  type: semver
  source:
    initial_version: "0.1.0"
    driver: git
    uri: git@github.com:boclips/versions.git
    branch: master
    file: lti
    private_key: ((versions-repo-key))

- name: image-lti
  type: docker-image
  source:
    repository: eu.gcr.io/boclips-prod/boclips/lti
    username: _json_key
    password: ((gcs-key))

- name: once-per-weekday
  type: time
  source:
    start: 09:30 AM
    stop: 12:30 PM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    location: Europe/London
