#!/usr/bin/env bash

set -eu

cwd="$(cd "$(dirname "$0")" && pwd)"

fly --target ci \
    set-pipeline \
    --pipeline lti \
    --config "$cwd/pipeline.yml" \
    --var lti-repo-key="$(lpass show concourse-lti-repo-key --notes)" \
    --var versions-repo-key="$(lpass show concourse-versions-repo-key --notes)" \
    --var gcs-key="$(lpass show concourse-gcs-service-account-key --notes)"
