boclips:
  api:
    baseUrl: 'https://api.staging-boclips.com'
    tokenUrl: 'https://api.staging-boclips.com/v1/token'

keycloak:
  configurationFile: 'classpath:keycloak-staging.json'

spring:
  mvc:
    favicon:
      enabled: false
