server:
  port: 8081

boclips:
  api:
    baseUrl: 'https://api.staging-boclips.com'
    tokenUrl: 'https://api.staging-boclips.com/v1/token'
  session:
    useSecureCookie: false

keycloak:
  configurationFile: 'classpath:keycloak-staging.json'

spring:
  thymeleaf:
    cache: false
  data:
    mongodb:
      uri: 'mongodb://localhost:27017/lti-db'
