boclips:
  api:
    baseUrl: 'https://api.testing-boclips.com'
    tokenUrl: 'https://api.testing-boclips.com/v1/token'

keycloak:
  configurationFile: 'classpath:keycloak-testing.json'

fixtures:
  ltiOnePointOne:
    consumerKey:
    consumerSecret:
  apiClient:
    id:
    secret:
