keycloak:
  configurationFile: 'classpath:keycloak-testing.json'

spring:
  mvc:
    favicon:
      enabled: false

fixtures:
  ltiOnePointOne:
    consumerKey:
    consumerSecret:
  videosClient:
    id:
    secret:
