server:
  port: 8080

boclips:
  api:
    url: 'https://api.staging-boclips.com'

  lti:
    v1p1:
      consumer:
        key: 'local-development-key'
        secret: 'local-development-secret'
      errorPage: 'https://boclips.com/error'
