boclips:
  lti:
    gateway:
      services:
        apiUrl: 'https://api.boclips.com'

keycloak:
  configurationFile: 'classpath:keycloak-production.json'

spring:
  mvc:
    favicon:
      enabled: false
