server:
  port: 8080

boclips:
  lti:
    v1p1:
      consumer:
        key: 'local-development-key'
        secret: 'local-development-secret'
      landingPage: 'https://www.boclips.com'
      errorPage: 'https://www.boclips.com/error'
