boclips:
  api:
    baseUrl: 'https://api.testing-boclips.com'
    tokenUrl: 'https://api.testing-boclips.com/v1/token'

keycloak:
  configurationFile: 'classpath:keycloak-testing.json'

spring:
  mvc:
    favicon:
      enabled: false

fixtures:
  ltiOnePointOne:
    consumerKey:
    consumerSecret:
  videosClient:
    id:
    secret:
