logging:
  config: "classpath:logback.xml"

server:
  error:
    include-stacktrace: ALWAYS

boclips:
  lti:
    v1p3:
      nonceLifetimeInHours: 24
      maxTokenAgeInSeconds: 60

management:
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
