boclips:
  api:
    baseUrl: 'https://api.boclips.com'
    tokenUrl: 'https://api.boclips.com/v1/token'

keycloak:
  configurationFile: 'classpath:keycloak-production.json'

spring:
  mvc:
    favicon:
      enabled: false

server:
  error:
    include-stacktrace: ALWAYS
